name: floaty_chatheads_example
description: Demonstrates how to use the floaty_chatheads plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  floaty_chatheads:
    path: ../
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

dependency_overrides:
  floaty_chatheads:
    path: ../
  floaty_chatheads_android:
    path: ../../floaty_chatheads_android
  floaty_chatheads_ios:
    path: ../../floaty_chatheads_ios
  floaty_chatheads_platform_interface:
    path: ../../floaty_chatheads_platform_interface

flutter:
  uses-material-design: true
  assets:
    - assets/
