// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsFloatyChatheadsApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsFloatyChatheadsApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsFloatyChatheadsApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashFloatyChatheadsApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashFloatyChatheadsApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashFloatyChatheadsApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum OverlayFlagMessage: Int {
  case defaultFlag = 0
  case clickThrough = 1
  case focusPointer = 2
}

enum NotificationVisibilityMessage: Int {
  case visibilityPublic = 0
  case visibilitySecret = 1
  case visibilityPrivate = 2
}

/// Which screen edge(s) the chathead snaps to after being released.
enum SnapEdgeMessage: Int {
  /// Snap to the nearest horizontal edge (left or right). Default.
  case both = 0
  /// Always snap to the left edge.
  case left = 1
  /// Always snap to the right edge.
  case right = 2
  /// No snapping — the bubble stays where the user releases it.
  case none = 3
}

/// Animation style used when the chathead first appears on screen.
enum EntranceAnimationMessage: Int {
  /// No entrance animation — bubble appears at its initial position.
  case none = 0
  /// Bubble pops in with a scale spring (default).
  case pop = 1
  /// Bubble slides in from the nearest edge.
  case slideFromEdge = 2
  /// Bubble fades in.
  case fade = 3
}

/// Theming configuration for the chathead.
///
/// All color values are ARGB integers.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ChatHeadThemeMessage: Hashable {
  var badgeColor: Int64? = nil
  var badgeTextColor: Int64? = nil
  var bubbleBorderColor: Int64? = nil
  var bubbleBorderWidth: Double? = nil
  var bubbleShadowColor: Int64? = nil
  var closeTintColor: Int64? = nil
  /// Color palette forwarded to the overlay isolate.
  /// Keys: primary, secondary, surface, background, onPrimary, etc.
  var overlayPalette: [String?: Int64?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatHeadThemeMessage? {
    let badgeColor: Int64? = nilOrValue(pigeonVar_list[0])
    let badgeTextColor: Int64? = nilOrValue(pigeonVar_list[1])
    let bubbleBorderColor: Int64? = nilOrValue(pigeonVar_list[2])
    let bubbleBorderWidth: Double? = nilOrValue(pigeonVar_list[3])
    let bubbleShadowColor: Int64? = nilOrValue(pigeonVar_list[4])
    let closeTintColor: Int64? = nilOrValue(pigeonVar_list[5])
    let overlayPalette: [String?: Int64?]? = nilOrValue(pigeonVar_list[6])

    return ChatHeadThemeMessage(
      badgeColor: badgeColor,
      badgeTextColor: badgeTextColor,
      bubbleBorderColor: bubbleBorderColor,
      bubbleBorderWidth: bubbleBorderWidth,
      bubbleShadowColor: bubbleShadowColor,
      closeTintColor: closeTintColor,
      overlayPalette: overlayPalette
    )
  }
  func toList() -> [Any?] {
    return [
      badgeColor,
      badgeTextColor,
      bubbleBorderColor,
      bubbleBorderWidth,
      bubbleShadowColor,
      closeTintColor,
      overlayPalette,
    ]
  }
  static func == (lhs: ChatHeadThemeMessage, rhs: ChatHeadThemeMessage) -> Bool {
    return deepEqualsFloatyChatheadsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFloatyChatheadsApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChatHeadConfig: Hashable {
  var entryPoint: String
  var contentWidth: Int64? = nil
  var contentHeight: Int64? = nil
  var chatheadIconAsset: String? = nil
  var closeIconAsset: String? = nil
  var closeBackgroundAsset: String? = nil
  var notificationTitle: String? = nil
  var notificationIconAsset: String? = nil
  var flag: OverlayFlagMessage
  var enableDrag: Bool
  var notificationVisibility: NotificationVisibilityMessage
  /// Which screen edge(s) the chathead snaps to.
  var snapEdge: SnapEdgeMessage
  /// Margin (in dp) from the screen edge when snapped.
  /// Negative values mean the bubble overlaps the edge (partially hidden).
  var snapMargin: Double
  /// Whether to save and restore the chathead position across sessions.
  var persistPosition: Bool
  /// The entrance animation when the chathead first appears.
  var entranceAnimation: EntranceAnimationMessage
  /// Optional theme configuration.
  var theme: ChatHeadThemeMessage? = nil
  /// Whether to enable the debug overlay inspector.
  var debugMode: Bool
  /// Whether the chathead automatically appears when the app goes to background.
  var autoLaunchOnBackground: Bool
  /// Whether the chathead overlay survives after the main app is killed.
  var persistOnAppClose: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatHeadConfig? {
    let entryPoint = pigeonVar_list[0] as! String
    let contentWidth: Int64? = nilOrValue(pigeonVar_list[1])
    let contentHeight: Int64? = nilOrValue(pigeonVar_list[2])
    let chatheadIconAsset: String? = nilOrValue(pigeonVar_list[3])
    let closeIconAsset: String? = nilOrValue(pigeonVar_list[4])
    let closeBackgroundAsset: String? = nilOrValue(pigeonVar_list[5])
    let notificationTitle: String? = nilOrValue(pigeonVar_list[6])
    let notificationIconAsset: String? = nilOrValue(pigeonVar_list[7])
    let flag = pigeonVar_list[8] as! OverlayFlagMessage
    let enableDrag = pigeonVar_list[9] as! Bool
    let notificationVisibility = pigeonVar_list[10] as! NotificationVisibilityMessage
    let snapEdge = pigeonVar_list[11] as! SnapEdgeMessage
    let snapMargin = pigeonVar_list[12] as! Double
    let persistPosition = pigeonVar_list[13] as! Bool
    let entranceAnimation = pigeonVar_list[14] as! EntranceAnimationMessage
    let theme: ChatHeadThemeMessage? = nilOrValue(pigeonVar_list[15])
    let debugMode = pigeonVar_list[16] as! Bool
    let autoLaunchOnBackground = pigeonVar_list[17] as! Bool
    let persistOnAppClose = pigeonVar_list[18] as! Bool

    return ChatHeadConfig(
      entryPoint: entryPoint,
      contentWidth: contentWidth,
      contentHeight: contentHeight,
      chatheadIconAsset: chatheadIconAsset,
      closeIconAsset: closeIconAsset,
      closeBackgroundAsset: closeBackgroundAsset,
      notificationTitle: notificationTitle,
      notificationIconAsset: notificationIconAsset,
      flag: flag,
      enableDrag: enableDrag,
      notificationVisibility: notificationVisibility,
      snapEdge: snapEdge,
      snapMargin: snapMargin,
      persistPosition: persistPosition,
      entranceAnimation: entranceAnimation,
      theme: theme,
      debugMode: debugMode,
      autoLaunchOnBackground: autoLaunchOnBackground,
      persistOnAppClose: persistOnAppClose
    )
  }
  func toList() -> [Any?] {
    return [
      entryPoint,
      contentWidth,
      contentHeight,
      chatheadIconAsset,
      closeIconAsset,
      closeBackgroundAsset,
      notificationTitle,
      notificationIconAsset,
      flag,
      enableDrag,
      notificationVisibility,
      snapEdge,
      snapMargin,
      persistPosition,
      entranceAnimation,
      theme,
      debugMode,
      autoLaunchOnBackground,
      persistOnAppClose,
    ]
  }
  static func == (lhs: ChatHeadConfig, rhs: ChatHeadConfig) -> Bool {
    return deepEqualsFloatyChatheadsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFloatyChatheadsApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayPositionMessage: Hashable {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayPositionMessage? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return OverlayPositionMessage(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: OverlayPositionMessage, rhs: OverlayPositionMessage) -> Bool {
    return deepEqualsFloatyChatheadsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFloatyChatheadsApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AddChatHeadConfig: Hashable {
  var id: String
  var iconAsset: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AddChatHeadConfig? {
    let id = pigeonVar_list[0] as! String
    let iconAsset: String? = nilOrValue(pigeonVar_list[1])

    return AddChatHeadConfig(
      id: id,
      iconAsset: iconAsset
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      iconAsset,
    ]
  }
  static func == (lhs: AddChatHeadConfig, rhs: AddChatHeadConfig) -> Bool {
    return deepEqualsFloatyChatheadsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashFloatyChatheadsApi(value: toList(), hasher: &hasher)
  }
}

private class FloatyChatheadsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OverlayFlagMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NotificationVisibilityMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SnapEdgeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EntranceAnimationMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return ChatHeadThemeMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return ChatHeadConfig.fromList(self.readValue() as! [Any?])
    case 135:
      return OverlayPositionMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return AddChatHeadConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FloatyChatheadsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OverlayFlagMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NotificationVisibilityMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SnapEdgeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? EntranceAnimationMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? ChatHeadThemeMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ChatHeadConfig {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayPositionMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AddChatHeadConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FloatyChatheadsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FloatyChatheadsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FloatyChatheadsApiPigeonCodecWriter(data: data)
  }
}

class FloatyChatheadsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FloatyChatheadsApiPigeonCodec(readerWriter: FloatyChatheadsApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FloatyHostApi {
  func checkPermission() throws -> Bool
  func requestPermission(completion: @escaping (Result<Bool, Error>) -> Void)
  func showChatHead(config: ChatHeadConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func closeChatHead() throws
  func isChatHeadActive() throws -> Bool
  func addChatHead(config: AddChatHeadConfig, completion: @escaping (Result<Void, Error>) -> Void)
  func removeChatHead(id: String) throws
  /// Updates the badge count on the chathead bubble.
  /// Pass 0 to hide the badge.
  func updateBadge(count: Int64) throws
  /// Programmatically expands the chathead to show its content panel.
  func expandChatHead() throws
  /// Programmatically collapses the chathead content panel.
  func collapseChatHead() throws
  /// Updates the chathead icon with raw RGBA pixel data.
  ///
  /// On iOS the chathead is already a Flutter view, so this is a
  /// no-op placeholder for API symmetry. The Dart-side
  /// [AnimatedWidgetIcon] renders directly via the overlay engine.
  func updateChatHeadIcon(id: String, rgbaBytes: FlutterStandardTypedData, width: Int64, height: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FloatyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FloatyChatheadsApiPigeonCodec.shared }
  /// Sets up an instance of `FloatyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FloatyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkPermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let showChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.showChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ChatHeadConfig
        api.showChatHead(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showChatHeadChannel.setMessageHandler(nil)
    }
    let closeChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.closeChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChatHeadChannel.setMessageHandler { _, reply in
        do {
          try api.closeChatHead()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChatHeadChannel.setMessageHandler(nil)
    }
    let isChatHeadActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.isChatHeadActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isChatHeadActiveChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isChatHeadActive()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isChatHeadActiveChannel.setMessageHandler(nil)
    }
    let addChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.addChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! AddChatHeadConfig
        api.addChatHead(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addChatHeadChannel.setMessageHandler(nil)
    }
    let removeChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.removeChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.removeChatHead(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChatHeadChannel.setMessageHandler(nil)
    }
    /// Updates the badge count on the chathead bubble.
    /// Pass 0 to hide the badge.
    let updateBadgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.updateBadge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateBadgeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          try api.updateBadge(count: countArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateBadgeChannel.setMessageHandler(nil)
    }
    /// Programmatically expands the chathead to show its content panel.
    let expandChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.expandChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      expandChatHeadChannel.setMessageHandler { _, reply in
        do {
          try api.expandChatHead()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      expandChatHeadChannel.setMessageHandler(nil)
    }
    /// Programmatically collapses the chathead content panel.
    let collapseChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.collapseChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      collapseChatHeadChannel.setMessageHandler { _, reply in
        do {
          try api.collapseChatHead()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      collapseChatHeadChannel.setMessageHandler(nil)
    }
    /// Updates the chathead icon with raw RGBA pixel data.
    ///
    /// On iOS the chathead is already a Flutter view, so this is a
    /// no-op placeholder for API symmetry. The Dart-side
    /// [AnimatedWidgetIcon] renders directly via the overlay engine.
    let updateChatHeadIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.updateChatHeadIcon\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChatHeadIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let rgbaBytesArg = args[1] as! FlutterStandardTypedData
        let widthArg = args[2] as! Int64
        let heightArg = args[3] as! Int64
        do {
          try api.updateChatHeadIcon(id: idArg, rgbaBytes: rgbaBytesArg, width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChatHeadIconChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FloatyOverlayHostApi {
  func resizeContent(width: Int64, height: Int64) throws
  func updateFlag(flag: OverlayFlagMessage) throws
  func closeOverlay() throws
  func getOverlayPosition() throws -> OverlayPositionMessage
  /// Updates the badge count from the overlay isolate.
  func updateBadgeFromOverlay(count: Int64) throws
  /// Returns debug information when debugMode is enabled.
  func getDebugInfo() throws -> [String?: Any?]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FloatyOverlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FloatyChatheadsApiPigeonCodec.shared }
  /// Sets up an instance of `FloatyOverlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FloatyOverlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let resizeContentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.resizeContent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resizeContentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.resizeContent(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resizeContentChannel.setMessageHandler(nil)
    }
    let updateFlagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.updateFlag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateFlagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let flagArg = args[0] as! OverlayFlagMessage
        do {
          try api.updateFlag(flag: flagArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateFlagChannel.setMessageHandler(nil)
    }
    let closeOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.closeOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeOverlayChannel.setMessageHandler { _, reply in
        do {
          try api.closeOverlay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeOverlayChannel.setMessageHandler(nil)
    }
    let getOverlayPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.getOverlayPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOverlayPositionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOverlayPosition()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOverlayPositionChannel.setMessageHandler(nil)
    }
    /// Updates the badge count from the overlay isolate.
    let updateBadgeFromOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.updateBadgeFromOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateBadgeFromOverlayChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          try api.updateBadgeFromOverlay(count: countArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateBadgeFromOverlayChannel.setMessageHandler(nil)
    }
    /// Returns debug information when debugMode is enabled.
    let getDebugInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.getDebugInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDebugInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDebugInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDebugInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FloatyOverlayFlutterApiProtocol {
  func onChatHeadTapped(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onChatHeadClosed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the content panel is expanded.
  func onChatHeadExpanded(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the content panel is collapsed.
  func onChatHeadCollapsed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the user starts dragging the chathead.
  func onChatHeadDragStart(id idArg: String, x xArg: Double, y yArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the user stops dragging the chathead.
  func onChatHeadDragEnd(id idArg: String, x xArg: Double, y yArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FloatyOverlayFlutterApi: FloatyOverlayFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FloatyChatheadsApiPigeonCodec {
    return FloatyChatheadsApiPigeonCodec.shared
  }
  func onChatHeadTapped(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onChatHeadClosed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the content panel is expanded.
  func onChatHeadExpanded(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadExpanded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the content panel is collapsed.
  func onChatHeadCollapsed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadCollapsed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the user starts dragging the chathead.
  func onChatHeadDragStart(id idArg: String, x xArg: Double, y yArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadDragStart\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg, xArg, yArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the user stops dragging the chathead.
  func onChatHeadDragEnd(id idArg: String, x xArg: Double, y yArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadDragEnd\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg, xArg, yArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
