// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum OverlayFlagMessage: Int {
  case defaultFlag = 0
  case clickThrough = 1
  case focusPointer = 2
}

enum NotificationVisibilityMessage: Int {
  case visibilityPublic = 0
  case visibilitySecret = 1
  case visibilityPrivate = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChatHeadConfig {
  var entryPoint: String
  var contentWidth: Int64? = nil
  var contentHeight: Int64? = nil
  var chatheadIconAsset: String? = nil
  var closeIconAsset: String? = nil
  var closeBackgroundAsset: String? = nil
  var notificationTitle: String? = nil
  var notificationIconAsset: String? = nil
  var flag: OverlayFlagMessage
  var enableDrag: Bool
  var notificationVisibility: NotificationVisibilityMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatHeadConfig? {
    let entryPoint = pigeonVar_list[0] as! String
    let contentWidth: Int64? = nilOrValue(pigeonVar_list[1])
    let contentHeight: Int64? = nilOrValue(pigeonVar_list[2])
    let chatheadIconAsset: String? = nilOrValue(pigeonVar_list[3])
    let closeIconAsset: String? = nilOrValue(pigeonVar_list[4])
    let closeBackgroundAsset: String? = nilOrValue(pigeonVar_list[5])
    let notificationTitle: String? = nilOrValue(pigeonVar_list[6])
    let notificationIconAsset: String? = nilOrValue(pigeonVar_list[7])
    let flag = pigeonVar_list[8] as! OverlayFlagMessage
    let enableDrag = pigeonVar_list[9] as! Bool
    let notificationVisibility = pigeonVar_list[10] as! NotificationVisibilityMessage

    return ChatHeadConfig(
      entryPoint: entryPoint,
      contentWidth: contentWidth,
      contentHeight: contentHeight,
      chatheadIconAsset: chatheadIconAsset,
      closeIconAsset: closeIconAsset,
      closeBackgroundAsset: closeBackgroundAsset,
      notificationTitle: notificationTitle,
      notificationIconAsset: notificationIconAsset,
      flag: flag,
      enableDrag: enableDrag,
      notificationVisibility: notificationVisibility
    )
  }
  func toList() -> [Any?] {
    return [
      entryPoint,
      contentWidth,
      contentHeight,
      chatheadIconAsset,
      closeIconAsset,
      closeBackgroundAsset,
      notificationTitle,
      notificationIconAsset,
      flag,
      enableDrag,
      notificationVisibility,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OverlayPositionMessage {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OverlayPositionMessage? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return OverlayPositionMessage(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AddChatHeadConfig {
  var id: String
  var iconAsset: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AddChatHeadConfig? {
    let id = pigeonVar_list[0] as! String
    let iconAsset: String? = nilOrValue(pigeonVar_list[1])

    return AddChatHeadConfig(
      id: id,
      iconAsset: iconAsset
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      iconAsset,
    ]
  }
}

private class FloatyChatheadsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OverlayFlagMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NotificationVisibilityMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return ChatHeadConfig.fromList(self.readValue() as! [Any?])
    case 132:
      return OverlayPositionMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return AddChatHeadConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FloatyChatheadsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OverlayFlagMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NotificationVisibilityMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ChatHeadConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OverlayPositionMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AddChatHeadConfig {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FloatyChatheadsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FloatyChatheadsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FloatyChatheadsApiPigeonCodecWriter(data: data)
  }
}

class FloatyChatheadsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FloatyChatheadsApiPigeonCodec(readerWriter: FloatyChatheadsApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FloatyHostApi {
  func checkPermission() throws -> Bool
  func requestPermission(completion: @escaping (Result<Bool, Error>) -> Void)
  func showChatHead(config: ChatHeadConfig) throws
  func closeChatHead() throws
  func isChatHeadActive() throws -> Bool
  func addChatHead(config: AddChatHeadConfig) throws
  func removeChatHead(id: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FloatyHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FloatyChatheadsApiPigeonCodec.shared }
  /// Sets up an instance of `FloatyHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FloatyHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let checkPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.checkPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.checkPermission()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkPermissionChannel.setMessageHandler(nil)
    }
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let showChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.showChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ChatHeadConfig
        do {
          try api.showChatHead(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showChatHeadChannel.setMessageHandler(nil)
    }
    let closeChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.closeChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChatHeadChannel.setMessageHandler { _, reply in
        do {
          try api.closeChatHead()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeChatHeadChannel.setMessageHandler(nil)
    }
    let isChatHeadActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.isChatHeadActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isChatHeadActiveChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isChatHeadActive()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isChatHeadActiveChannel.setMessageHandler(nil)
    }
    let addChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.addChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! AddChatHeadConfig
        do {
          try api.addChatHead(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addChatHeadChannel.setMessageHandler(nil)
    }
    let removeChatHeadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyHostApi.removeChatHead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChatHeadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.removeChatHead(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChatHeadChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FloatyOverlayHostApi {
  func resizeContent(width: Int64, height: Int64) throws
  func updateFlag(flag: OverlayFlagMessage) throws
  func closeOverlay() throws
  func getOverlayPosition() throws -> OverlayPositionMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FloatyOverlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FloatyChatheadsApiPigeonCodec.shared }
  /// Sets up an instance of `FloatyOverlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FloatyOverlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let resizeContentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.resizeContent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resizeContentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          try api.resizeContent(width: widthArg, height: heightArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resizeContentChannel.setMessageHandler(nil)
    }
    let updateFlagChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.updateFlag\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateFlagChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let flagArg = args[0] as! OverlayFlagMessage
        do {
          try api.updateFlag(flag: flagArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateFlagChannel.setMessageHandler(nil)
    }
    let closeOverlayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.closeOverlay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeOverlayChannel.setMessageHandler { _, reply in
        do {
          try api.closeOverlay()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeOverlayChannel.setMessageHandler(nil)
    }
    let getOverlayPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayHostApi.getOverlayPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOverlayPositionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getOverlayPosition()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getOverlayPositionChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FloatyOverlayFlutterApiProtocol {
  func onChatHeadTapped(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onChatHeadClosed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FloatyOverlayFlutterApi: FloatyOverlayFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FloatyChatheadsApiPigeonCodec {
    return FloatyChatheadsApiPigeonCodec.shared
  }
  func onChatHeadTapped(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onChatHeadClosed(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.floaty_chatheads.FloatyOverlayFlutterApi.onChatHeadClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
