name: floaty_chatheads
description: >
  Floating chathead plugin for Android & iOS with draggable bubbles,
  expandable content panels, theming, snap-to-edge physics, and
  bidirectional app-overlay messaging.
version: 1.2.0
homepage: https://github.com/crdzbird/floaty_chatheads
repository: https://github.com/crdzbird/floaty_chatheads
issue_tracker: https://github.com/crdzbird/floaty_chatheads/issues
topics:
  - overlay
  - chathead
  - floating-window
  - widget
  - pip

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: floaty_chatheads_android
      ios:
        default_package: floaty_chatheads_ios

dependencies:
  floaty_chatheads_android: ^1.0.0
  floaty_chatheads_ios: ^1.1.0
  floaty_chatheads_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
